include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_this: true
    always_declare_return_types: true
    prefer_single_quotes: true
    directives_ordering: true
