name: flashxp
description: A flashcard learning app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.0
  go_router: ^13.0.1
  font_awesome_flutter: ^10.8.0
  flutter_animate: ^4.5.2
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  http: ^1.4.0
  file_picker: ^10.3.1
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
