// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:flashxp/shared/config/firebase.options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZbKHIH0TOYKDxc5Lp1aKw1dzyNdrRJ4',
    appId: '1:175799746960:web:8b89b6183d2afdc3283315',
    messagingSenderId: '175799746960',
    projectId: 'flashxp',
    authDomain: 'flashxp.firebaseapp.com',
    storageBucket: 'flashxp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCahmCIlQV9TIpqSA8ZQXTXRjyfJ_8Ow-k',
    appId: '1:175799746960:android:ec4379200005aaa3283315',
    messagingSenderId: '175799746960',
    projectId: 'flashxp',
    storageBucket: 'flashxp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClhYmWYzyHBDK5B5B3ucbHEUplHX9mbXA',
    appId: '1:175799746960:ios:ec3536db225412aa283315',
    messagingSenderId: '175799746960',
    projectId: 'flashxp',
    storageBucket: 'flashxp.firebasestorage.app',
    iosBundleId: 'com.example.flashxp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClhYmWYzyHBDK5B5B3ucbHEUplHX9mbXA',
    appId: '1:175799746960:ios:ec3536db225412aa283315',
    messagingSenderId: '175799746960',
    projectId: 'flashxp',
    storageBucket: 'flashxp.firebasestorage.app',
    iosBundleId: 'com.example.flashxp',
  );
}
